### ISSUE TITLE
Raised a MemoryError after called decompose.process

### ISSUE THREAD

**Issue by okideal** [faroit/commonfate#5]
**code:**
`(audio, fs) = sf.read('1.wav', always_2d=True)
    components = commonfate.decompose.process(
        audio,
        nb_components=10,
    )
    sf.write(
        "comp_3.wav",
        components[2, ...],
        fs
    )`
**raise errors:**
Traceback (most recent call last):
  File "F:/py_project/independent-project.git/music_ctl_lettin/music_feature_engineering/process_music.py", line 190, in <module>
    nb_components=10,
  File "C:\Users\Besitzer\AppData\Local\Programs\Python\Python36-32\lib\site-packages\commonfate\decompose.py", line 63, in process
    n_hop,
  File "C:\Users\Besitzer\AppData\Local\Programs\Python\Python36-32\lib\site-packages\commonfate\transform.py", line 325, in forward
    stft = fftFunction(stft, frameShape, axes=range(len(frameShape)))
  File "C:\Users\Besitzer\AppData\Local\Programs\Python\Python36-32\lib\site-packages\numpy\fft\fftpack.py", line 1099, in rfftn
    a = rfft(a, s[-1], axes[-1], norm)
  File "C:\Users\Besitzer\AppData\Local\Programs\Python\Python36-32\lib\site-packages\numpy\fft\fftpack.py", line 372, in rfft
    _real_fft_cache)
  File "C:\Users\Besitzer\AppData\Local\Programs\Python\Python36-32\lib\site-packages\numpy\fft\fftpack.py", line 83, in _raw_fft
    r = work_function(a, wsave)
MemoryError

Any ideas?

**Comment by faroit** [comment]
It's always the same error? What's the file size? Have you tried with smaller files and less components?
